### ISSUE TITLE
Unquoted Service Path in Installer

### ISSUE THREAD

**Issue by Derekt2** [godaddy/procfilter#15]
Looks like the installer leaves an unquoted service path. It is still function, but leaves hosts with it installed vulnerable to privilege escalation. 
![image](https://user-images.githubusercontent.com/28223951/70674384-72100980-1c4b-11ea-874f-64ddfbaebea9.png)

**Comment by ewil** [comment]
Sorry about this, I never got an alert that this issue was filed and only noticed it yesterday. You are correct and this will be fixed in the next build.
